config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'movies#index'
  get 'movies', to: 'movies#index'
  get 'movies/new', to: 'movies#new'
  post 'movies', to: 'movies#create'
  get 'movies/:id', to: 'movies#show', as: :movie
  get 'movies/:id/edit', to: 'movies#edit', as: :edit_movie
  patch 'movies/:id', to: 'movies#update'
  delete 'movies/:id', to: 'movies#destroy'

  get 'movies/:id/list', to: 'lists#new', as: :new_list

  post 'list', to: 'lists#create', as: :create_list
  get 'list/:id', to: 'lists#show', as: :list
  delete 'list/:id', to: 'lists#destroy', as: :delete_list
  get 'list/:id/edit', to: 'lists#edit', as: :edit_list
  patch 'list/:id', to: 'lists#update', as: :update_list



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: :true
  validates :overview, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_controller.rb
class ListController < ApplicationController

  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<%  @movies.each do |movie| %>
  <h1><%= movie.title %> - <small><%= movie.rating %></small></h1>
  <p><%= movie.overview %></p>
  <%= link_to 'Show', movie_path(movie), class:"btn btn-primary" %>
  <hr>
<% end %>

app/views/movies/show.html.erb
<%= @movie.title %>
<%= @movie.rating %>
<%= @movie.overview %>

<%= link_to 'Edit', edit_movie_path(@movie) %>
<%= link_to 'Destroy', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', movies_path %>